ROX-2997: Fix bug in resumable restore related to --interrupt (stackrox/rox#3112)

diff --git a/image/static-bin/restore-central-db b/image/static-bin/restore-central-db
--- a/image/static-bin/restore-central-db
+++ b/image/static-bin/restore-central-db
@@ -9,5 +9,7 @@ if [ -d "/var/lib/stackrox/.restore" ]; then
 	mv /var/lib/stackrox/.restore/* /var/lib/stackrox/
 	rmdir /var/lib/stackrox/.restore
 else
-	echo "No database restore directory found."
+	echo "No database restore directory found (this is not an error)."
 fi
+
+rm -rf /var/lib/stackrox/.restore-* 2>/dev/null || true
