CI: retry and debug for upgrade test failure (stackrox/rox#8112)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4156,7 +4156,22 @@ jobs:
       - run:
           name: Fetch bundle for the "remote" cluster in the DB
           command: |
-            roxctl -e "${API_ENDPOINT}" -p "${ROX_PASSWORD}" sensor get-bundle remote
+            success=0
+            max_tries=5
+            for i in $(seq 1 "${max_tries}"); do
+              if roxctl -e "${API_ENDPOINT}" -p "${ROX_PASSWORD}" sensor get-bundle remote; then
+                success=1
+                break
+              fi
+              kubectl -n stackrox get pods || true
+              kubectl -n stackrox logs -l app=central || true
+              echo "Retrying in 5 seconds (failed ${i} times)"
+              sleep 5
+            done
+            if [[ "${success}" == 0 ]]; then
+              echo "Failed after ${max_tries} tries"
+              exit 1
+            fi
             [[ -d sensor-remote ]]
 
       - run:
