restore warn if defaults also

diff --git a/.github/actions/job-preamble/action.yaml b/.github/actions/job-preamble/action.yaml
--- a/.github/actions/job-preamble/action.yaml
+++ b/.github/actions/job-preamble/action.yaml
@@ -3,8 +3,6 @@ description: Common steps for most jobs
 inputs:
   free-disk-space:
     description: 'Free disk space desired in GB (2025-06 ubuntu-24.04 runner starts with 20GB free and we can delete and reach 40GB)'
-  default-free-disk-space:
-    description: 'default for free-disk-space'
     default: 25
   gcp-account:
     description: 'Account to be used to upload tests data'
@@ -12,11 +10,6 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Variable setup
-      shell: bash
-      run: |
-        echo "target_free=${{ inputs.free-disk-space || inputs.default-free-disk-space }}" >> $GITHUB_ENV
-
     - name: Set up gcloud CLI
       uses: 'google-github-actions/setup-gcloud@v2'
 
@@ -44,28 +37,18 @@ runs:
       shell: bash
       run: |
         set +e
-        du -k /__t/ | sort -V
         if [[ -d "/__t" ]]; then
           set -x
-          # 2025-07-09 'rm -rf /__t/*' takes around 18-20 seconds and reach 30gb free. 
-          time rm -rf /__t/CodeQL /__t/Python /__t/gcloud /__t/go /__t/node
+          time rm -rf /__t/CodeQL /__t/Python /__t/go /__t/gcloud /__t/node /__t/PyPy /__t/Ruby
           free=$(df -BGB --output=avail / | tail -1)
-          if [[ ${free%GB} -lt "${{ env.target_free }}" ]]; then
-            echo "Failed to free requested disk space, ${{ env.target_free }} [${free} free]."
+          if [[ ${free%GB} -lt "${{ inputs.free-disk-space }}" ]]; then
+            echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]."
+            exit 1
           else
             exit 0
           fi
         fi
         cleanup=(
-          /__t/CodeQL
-          /__t/Python
-          /__t/go
-          /__t/gcloud
-          /__t/PyPy
-          /__t/node
-          /__t/Ruby
-          /__t/Java_Temurin-Hotspot_jdk
-
           # on non-container jobs:
           /usr/share/dotnet
           /usr/share/miniconda
@@ -79,8 +62,8 @@ runs:
         )
         for d in "${cleanup[@]}"; do
           free=$(df -BGB --output=avail / | tail -1)
-          if [[ ${free%GB} -ge "${{ env.target_free }}" ]]; then
-            echo "Reached requested free disk space ${{ env.target_free }} [${free} free]."
+          if [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]; then
+            echo "Reached requested free disk space ${{ inputs.free-disk-space }} [${free} free]."
             exit 0
           fi
           if [[ -d "$d" ]]; then
@@ -91,8 +74,8 @@ runs:
         done
         df --si /
         free=$(df -BGB --output=avail / | tail -1)
-        if [[ ${free%GB} -lt "${{ env.target_free }}" ]]; then
-          echo "Failed to free requested disk space, ${{ env.target_free }} [${free} free]."
+        if [[ ${free%GB} -lt "${{ inputs.free-disk-space  }}" ]]; then
+          echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]."
           exit 1
         fi
 
@@ -106,21 +89,21 @@ runs:
         docker system prune --force --all
         df --si /
         free=$(df -BGB --output=avail / | tail -1)
-        if [[ ${free%GB} -lt "${{ env.target_free }}" ]]; then
-          echo "Failed to free requested disk space, ${{ env.target_free }} [${free} free]."
+        if [[ ${free%GB} -lt "${{ inputs.free-disk-space }}" ]]; then
+          echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]."
           exit 1
         fi
 
     - name: Verify free disk space
-      if: (steps.delete-docker-cache.outcome == 'failure') && (inputs.free-disk-space && true || false)  # Do not warn if default free space
+      if: steps.delete-docker-cache.outcome == 'failure'
       continue-on-error: true
       shell: bash
       run: |
         free=$(df -BGB --output=avail / | tail -1)
-        echo "Failed to free requested disk space, ${{ env.target_free }} [${free} free]." \
+        echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]." \
           | tee -a "$GITHUB_STEP_SUMMARY"
         df -BGB /
-        [[ ${free%GB} -ge "${{ env.target_free }}" ]]
+        [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]
 
     - name: Ignore dubious repository ownership
       run: |
