chore(ci): in gha, [preamble] free only to target free space (#15634)

diff --git a/.github/actions/job-preamble/action.yaml b/.github/actions/job-preamble/action.yaml
--- a/.github/actions/job-preamble/action.yaml
+++ b/.github/actions/job-preamble/action.yaml
@@ -4,7 +4,7 @@ inputs:
   free-disk-space:
     description: 'Free disk space desired in GB (2025-06 ubuntu-24.04 runner starts with 20GB free and we can delete and reach 40GB)'
     required: false
-    default: 25
+    default: 22
   gcp-account:
     description: 'Account to be used to upload tests data'
     required: true
@@ -15,8 +15,8 @@ runs:
       uses: 'google-github-actions/setup-gcloud@v2'
 
     - name: Shim gsutil as gcloud storage
-      shell: bash
       continue-on-error: true
+      shell: bash
       run: |
         tee -a ~/.boto <<EOF
         [GSUtil]
@@ -25,59 +25,30 @@ runs:
         gsutil version -l
 
     - name: Recover docker image cache space
+      shell: bash
       run: |
         df --si /
         printf 'Docker prune: '
         docker system prune --force --all
         df --si /
-      shell: bash
 
-    - name: Check gcloud CLI
-      id: gcloud-check
-      continue-on-error: true
-      shell: bash
-      run: |
-        which gcloud
-
-    # setup-gcloud authenticates gcloud
-    - name: Install gcloud CLI
-      uses: 'google-github-actions/setup-gcloud@v2'
-      with:
-        skip_install: ${{ steps.gcloud-check.outcome != 'failure' }}
-
-    - name: Shim gsutil as gcloud storage
-      continue-on-error: true
-      shell: bash
-      run: |
-        tee -a ~/.boto <<EOF
-        [GSUtil]
-        use_gcloud_storage=True
-        EOF
-
-    - name: Check disk space
+    - name: List filesystems
       id: disk-check
-      continue-on-error: true
       shell: bash
       run: |
+        df --si
         free=$(df -BGB --output=avail / | tail -1)
         echo "free=${free}" | tee -a "$GITHUB_OUTPUT"
-        if [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]; then
-          echo "Reached requested free disk space ${{ inputs.free-disk-space }} [${free} free]."
-          exit 0
-        else
-          df --si
-          exit 1
-        fi
 
-    - name: Free disk space (delete unused tools)
+    - name: Free disk space, delete unused tools
       id: delete-unused-tools
-      if: steps.disk-check.outcome == 'failure'
       continue-on-error: true
       shell: bash
       run: |
-        # delete preinstalled unused tools
+        set +e
+        # preinstalled tools not used. ordered by size asc
         cleanup=(
-          # non-container jobs are first priority (every second may be a high % of the total)
+          # always remove (on runner or container job):
           /usr/share/dotnet
           /usr/share/miniconda
           /usr/share/swift
@@ -87,34 +58,36 @@ runs:
           /opt/hostedtoolcache/Ruby
           /opt/az
           /usr/local/lib/android
-          # container jobs are lower priority: they are already slowed by container image pulls
-          /__t/CodeQL
-          /__t/Ruby
-          /__t/PyPy
-          /__t/Python
-          /__t/go
-          /__t/node
-          /__t/gcloud
+
+          # remove if container job:
+          /mnt/usr/local/lib/node_modules
+          /mnt/opt/hostedtoolcache/node
+          /mnt/opt/pipx
+          /mnt/opt/hostedtoolcache/Python
+          /mnt/opt/hostedtoolcache/go
         )
         for d in "${cleanup[@]}"; do
-          if [[ -d "$d" ]]; then
-            rm -rf -- "$d" && echo "deleted $d"
-          elif [[ -d "/mnt${d}" ]]; then
-            rm -rf -- "/mnt${d}" && echo "deleted /mnt${d}"
-          else
-            echo "$d not found"
-            continue
-          fi
           free=$(df -BGB --output=avail / | tail -1)
           if [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]; then
-            echo "Reached requested free disk space ${{ inputs.free-disk-space }} [${free} free]."
+            echo "Reached required free disk space ${{ inputs.free-disk-space }} [${free} free]."
             exit 0
           fi
+          if [[ -d "/mnt${d}" ]]; then
+            rm -rf "/mnt${d}"
+          elif [[ -d "$d" ]]; then
+            rm -rf "$d" \
+              || sudo rm -rf "$d"
+          fi
         done
-        echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]."
-        exit 1
+        df --si /
+        free=$(df -BGB --output=avail / | tail -1)
+        if [[ ${free%GB} -lt "${{ inputs.free-disk-space }}" ]]; then
+          printf "For container workflows, please mount the host /usr and /opt to allow deleting unused tools:\nvolumes:\n\t- /usr:/mnt/usr\n\t- /opt:/mnt/opt" \
+            | tee -a "$GITHUB_STEP_SUMMARY"
+          exit 1
+        fi
 
-    - name: Free more disk space (docker system prune)
+    - name: Free more disk space, docker system prune
       id: delete-docker-cache
       if: steps.delete-unused-tools.outcome == 'failure'
       continue-on-error: true
@@ -122,25 +95,20 @@ runs:
       run: |
         printf 'Docker prune: '
         docker system prune --force --all
+        df --si /
+        free=$(df -BGB --output=avail / | tail -1)
+        [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]
 
     - name: Verify free disk space
-      id: disk-check-cleaned
-      if: steps.disk-check.outcome == 'failure'
+      if: steps.delete-docker-cache.outcome == 'failure'
       continue-on-error: true
       shell: bash
       run: |
         free=$(df -BGB --output=avail / | tail -1)
-        echo "free=${free}" | tee -a "$GITHUB_OUTPUT"
-        if [[ ${free%GB} -lt "${{ inputs.free-disk-space }}" ]]; then
-          echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]." \
-            | tee -a "$GITHUB_STEP_SUMMARY"
-          if [[ ! -d /opt/hostedtoolcache && ! -d /mnt/opt/hostedtoolcache && ! -d /mnt/usr/local ]]; then
-            printf 'For container workflows, you can mount the host /usr and /opt to allow deleting more unused tools:\n```\nvolumes:\n\t- /usr:/mnt/usr\n\t- /opt:/mnt/opt\n```' \
-              | tee -a "$GITHUB_STEP_SUMMARY"
-          fi
-          df --si /
-          exit 1
-        fi
+        echo "Failed to free requested disk space, ${{ inputs.free-disk-space }} [${free} free]." \
+          | tee -a "$GITHUB_STEP_SUMMARY"
+        df -BGB /
+        [[ ${free%GB} -ge "${{ inputs.free-disk-space }}" ]]
 
     - name: Ignore dubious repository ownership
       run: |
@@ -161,12 +129,9 @@ runs:
         post: >
           source scripts/ci/lib.sh;
           update_job_record outcome "${{ job.status }}" stopped_at "CURRENT_TIMESTAMP()";
+          df --si /;
           free=$(df -BGB --output=avail / | tail -1);
-          echo "Free disk space before: ${{ steps.disk-check-cleaned.outputs.free }} [${{ steps.disk-check.outputs.free }} before cleanup], and after: ${free}.";
+          echo "Free disk space before: ${{ steps.disk-check.outputs.free }}, and after: ${free}.";
           if [[ ${free%GB} -lt 5 ]]; then\
-            set -ex;\
-            df --si;\
-            du -ks /* 2>/dev/null | sort -V || true;\
-            du -k / 2>/dev/null | sort -V | tail -100 || true; \
             printf "Low free disk space post-job: ${free}" | tee -a "$GITHUB_STEP_SUMMARY";\
           fi;
