delete all toolcache on container runs

diff --git a/.github/actions/job-preamble/action.yaml b/.github/actions/job-preamble/action.yaml
--- a/.github/actions/job-preamble/action.yaml
+++ b/.github/actions/job-preamble/action.yaml
@@ -30,14 +30,6 @@ runs:
         EOF
         gsutil version -l
 
-    - name: Recover docker image cache space
-      shell: bash
-      run: |
-        df --si /
-        printf 'Docker prune: '
-        docker system prune --force --all
-        df --si /
-
     - name: List filesystems
       id: disk-check
       shell: bash
@@ -52,18 +44,18 @@ runs:
       shell: bash
       run: |
         set +e
-        du -s /__t/* | sort -V
-        # preinstalled tools not used. ordered by size asc
+        if [[ -d "/__t" ]]; then
+          set -x
+          rm -rf /__t/*
+          free=$(df -BGB --output=avail / | tail -1)
+          if [[ ${free%GB} -lt "${{ env.target_free }}" ]]; then
+            echo "Failed to free requested disk space, ${{ env.target_free }} [${free} free]."
+            exit 1
+          else
+            exit 0
+          fi
+        fi
         cleanup=(
-          # remove if container job:
-          /__t/CodeQL
-          /__t/Python
-          /__t/go
-          /__t/gcloud
-          /__t/node
-          /__t/PyPy
-          /__t/Ruby
-
           # on non-container jobs:
           /usr/share/dotnet
           /usr/share/miniconda
