Add basic protection from running arbitrary targets
merely for us to not do anything weird accidentally.

diff --git a/.tekton/determine-image-tag-task.yaml b/.tekton/determine-image-tag-task.yaml
--- a/.tekton/determine-image-tag-task.yaml
+++ b/.tekton/determine-image-tag-task.yaml
@@ -49,5 +49,14 @@ spec:
       dnf -y install git make
 
       .konflux/scripts/fail-build-if-git-is-dirty.sh
+
+      # Basic protection against running something arbitrary.
+      allowed_targets="tag|collector-tag|scanner-tag"
+      if [[ "|${allowed_targets}|" != *"|$(params.MAKEFILE_TARGET)|"* ]]; then
+        >&2 echo "Error: provided MAKEFILE_TARGET $(params.MAKEFILE_TARGET) is not one of the allowed targets ${allowed_targets}"
+        exit 2
+      fi
+
       image_tag="$(make -C "$(params.MAKEFILE_DIRECTORY)" --quiet --no-print-directory "$(params.MAKEFILE_TARGET)")$(params.TAG_SUFFIX)"
+
       echo -n "$image_tag" | tee "$(results.IMAGE_TAG.path)"
