Adjust determine-image-tag-task to support git tags and unsuffixing

diff --git a/.tekton/determine-image-tag-task.yaml b/.tekton/determine-image-tag-task.yaml
--- a/.tekton/determine-image-tag-task.yaml
+++ b/.tekton/determine-image-tag-task.yaml
@@ -23,6 +23,17 @@ spec:
     description: Makefile target to run.
     type: string
     default: "tag"
+  - name: TARGET_BRANCH
+    description: Branch or tag that triggered a build pipeline with this task.
+      Must be set to {{ target_branch }} Pipelines as Code variable.
+      See https://pipelinesascode.com/docs/guide/authoringprs/#dynamic-variables
+    type: string
+  - name: SUPPRESS_TAG_SUFFIX_ON_TARGET_BRANCH_REGEX
+    description: Regular expression which, when matches TARGET_BRANCH param, prevents TAG_SUFFIX to be appended to the
+      resulting tag. Intended for Stable Stream builds where we want to produce image tags without the "-fast" suffix.
+      Set to release branches and release tags by default.
+    type: string
+    default: ^(release-.*|refs/tags/[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?)$
   results:
   - name: IMAGE_TAG
     description: Image Tag determined by custom logic.
@@ -50,13 +61,40 @@ spec:
 
       .konflux/scripts/fail-build-if-git-is-dirty.sh
 
-      # Basic protection against running something arbitrary.
-      allowed_targets="tag|collector-tag|scanner-tag"
-      if [[ "|${allowed_targets}|" != *"|$(params.MAKEFILE_TARGET)|"* ]]; then
-        >&2 echo "Error: provided MAKEFILE_TARGET $(params.MAKEFILE_TARGET) is not one of the allowed targets ${allowed_targets}"
+      suffix="$(params.TAG_SUFFIX)"
+      target="$(params.MAKEFILE_TARGET)"
+
+      if [[ "${target}" == "collector-tag" || "${target}" == "scanner-tag" ]]; then
+
+        # For dependencies (i.e. scanner and collector) tags, we always take what make returns. Konflux builds of
+        # scanner and collector don't replace quay.io/rhacs-eng/ builds that's why we currently locate Konflux images
+        # via the suffix.
+        image_tag="$(make -C "$(params.MAKEFILE_DIRECTORY)" --quiet --no-print-directory "${target}")${suffix}"
+
+      elif [[ "${target}" != "tag" ]]; then
+
+        >&2 echo "Error: provided MAKEFILE_TARGET ${target} is not recognized."
         exit 2
+
+      else # "${target}" is "tag"
+
+        target_branch="$(params.TARGET_BRANCH)"
+
+        if grep -qE '$(params.SUPPRESS_TAG_SUFFIX_ON_TARGET_BRANCH_REGEX)' <<< "${target_branch}"; then
+          echo "Target branch ${target_branch} matches regex, the image tag suffix ${suffix} will be omitted."
+          suffix=""
+        fi
+
+        if [[ "${target_branch}" == refs/tags/* ]]; then
+          echo "${target_branch} seems to be a build of a git tag, will use this git tag."
+          image_tag="${target_branch#refs/tags/}"
+        else
+          # Otherwise, delegate the work to Makefiles.
+          image_tag="$(make -C "$(params.MAKEFILE_DIRECTORY)" --quiet --no-print-directory "${target}")"
+        fi
+
+        image_tag="${image_tag}${suffix}"
+
       fi
 
-      image_tag="$(make -C "$(params.MAKEFILE_DIRECTORY)" --quiet --no-print-directory "$(params.MAKEFILE_TARGET)")$(params.TAG_SUFFIX)"
-
-      echo -n "$image_tag" | tee "$(results.IMAGE_TAG.path)"
+      echo -n "${image_tag}" | tee "$(results.IMAGE_TAG.path)"
