fixup! fixup! ROX-14475: Upgrade to UBI9
Turns out we weren't running the `update-ca-trust` command from the last
fixup since we were restoring `/etc/pki/ca-trust/extracted` that was
saved during the container build process. These changes should implement
the original fixup correctly and allow the operator-related CA tests to
pass.

diff --git a/image/rhel/static-bin/import-additional-cas b/image/rhel/static-bin/import-additional-cas
--- a/image/rhel/static-bin/import-additional-cas
+++ b/image/rhel/static-bin/import-additional-cas
@@ -26,11 +26,16 @@ copy_existing /etc/pki/injected-ca-trust
 
 # TODO(DO NOT MERGE): We can't override `/etc/pki/ca-trust/extracted` because
 #  some of the files don't have the write permission bit set.
-# TODO(DO NOT MERGE): If we agree with this approach, it could be simplified:
+# TODO(DO NOT MERGE): If we don't care about the warning, this can be
 #  [ ! -e "/etc/pki/ca-trust/extracted" ] || \
 #      update-ca-trust extract --output /etc/pki/ca-trust/extracted
-#  However, I don't really this approach to begin with.
-if [ ! -e "/etc/pki/ca-trust/extracted" ]; then
+if [ -e "/etc/pki/ca-trust/extracted" ]; then
+    # TODO(DO NOT MERGE): The sensor deployment calls this script twice (once
+    #  during an init container and another when the main container strats),
+    #  which means this warning will always be logged in the current sensor
+    #  deployments.
+    echo >&2 "Warning: CA trust list already configured. Can't overwrite."
+else
     # TODO(DO NOT MERGE): For some reason, without the `--output` flag,
     #  `update-ca-trust` expects `/etc/pki/ca-trust/extracted` to have all the
     #  necessary directories created. However, if run with the `--output` flag,
