separate warnings and errors

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -862,18 +862,19 @@ jobs:
           oc version || true
           rm oc.tar.gz
 
+      - name: install podman
+        run: |
+          sudo apt-get -y install podman || true
+          which podman || sudo apt-get -y install podman || true
+          podman -v
+
       - name: Scan images for FIPS compliance
         run: |
           set -x
           set +e
-          pwd
-          ls -la
           cd check-payload
-          ls -la
-          SHELL=/bin/bash
-          which podman || sudo apt-get -y install podman || true
-          podman -v
-          oc version || true
+          git log -1
+          # SHELL=/bin/bash
           image="${{ matrix.image }}"
           echo "image: ${image}" \
             | tee -a "$GITHUB_STEP_SUMMARY"
@@ -889,12 +890,20 @@ jobs:
           podman unshare go run main.go scan operator --verbose \
             --spec "quay.io/rhacs-eng/${image}:${tag}" 2>&1 \
             | tee /tmp/scan.log
-          ls -la /tmp/scan.log
-          cat /tmp/scan.log
-          grep 'status="\(failed\|warning\)"$' /tmp/scan.log \
+          exitcode=$?
+          echo "warnings:" \
+            >> "$GITHUB_STEP_SUMMARY"
+          grep 'status="warning"$' /tmp/scan.log \
             | grep -o 'path=.*error="[^"]*"' \
             >> "$GITHUB_STEP_SUMMARY" \
-            || true  # allow none found
+            || true  # allow no warnings found
+          echo "errors:" \
+            >> "$GITHUB_STEP_SUMMARY"
+          grep 'status="failed"$' /tmp/scan.log \
+            | grep -o 'path=.*error="[^"]*"' \
+            >> "$GITHUB_STEP_SUMMARY" \
+            || true  # allow no errors found
+          exit "${exitcode}"
 
   slack-on-build-failure:
     env:
