ROX-11711: various fixes on Cut RC

diff --git a/.github/workflows/cut-rc.yml b/.github/workflows/cut-rc.yml
--- a/.github/workflows/cut-rc.yml
+++ b/.github/workflows/cut-rc.yml
@@ -16,6 +16,21 @@ on:
         required: false
         default: true
         type: boolean
+      create-k8s-cluster:
+        description: Create a GKE demo cluster
+        required: true
+        default: true
+        type: boolean
+      create-os4-cluster:
+        description: Create an Openshift 4 demo cluster
+        required: true
+        default: true
+        type: boolean
+      create-long-cluster:
+        description: Create a long-running cluster on RC1
+        required: true
+        default: true
+        type: boolean
 
 env:
   main_branch: ${{github.event.repository.default_branch}}
@@ -209,6 +224,24 @@ jobs:
           git push --follow-tags
       - run: |
           echo "Release branch has been tagged with ${{needs.variables.outputs.milestone}}." >> $GITHUB_STEP_SUMMARY
+      - name: Create next milestone
+        if: env.DRY_RUN == 'false'
+        run: |
+          set -u
+          if ! http_code=$(gh api --silent -X POST \
+            "repos/${{github.repository}}/milestones" \
+            -f "title"="${{needs.variables.outputs.next-milestone}}" \
+            2>&1); then
+
+            if grep "HTTP 422" <<< "$http_code"; then
+              echo "Milestone ${{needs.variables.outputs.next-milestone}} already exists." >> $GITHUB_STEP_SUMMARY
+            else
+              echo "::error::Couldn't create milestone ${{needs.variables.outputs.next-milestone}}: $http_code"
+              exit 1
+            fi
+          else
+            echo "Milestone ${{needs.variables.outputs.next-milestone}} has been created." >> $GITHUB_STEP_SUMMARY
+          fi
 
   reopen-milestone:
     name: Reopen milestone ${{needs.variables.outputs.milestone}}
@@ -270,8 +303,8 @@ jobs:
   create-k8s-cluster:
     name: Create k8s cluster
     needs: [variables, cut-rc]
-    # Cannot use env.DRY_RUN here. `dry-run` can be 'true', 'false' or empty.
-    if: github.event.inputs.dry-run != 'true'
+    # Cannot use env.DRY_RUN here. `github.event.inputs.*` can be 'true', 'false' or empty.
+    if: github.event.inputs.dry-run != 'true' && github.event.inputs.create-gke-cluster != 'false'
     uses: ./.github/workflows/create-cluster.yml
     secrets: inherit
     with:
@@ -283,8 +316,8 @@ jobs:
   create-os4-cluster:
     name: Create OS4 cluster
     needs: [variables, cut-rc]
-    # Cannot use env.DRY_RUN here. `dry-run` can be 'true', 'false' or empty.
-    if: github.event.inputs.dry-run != 'true'
+    # Cannot use env.DRY_RUN here. `github.event.inputs.*` can be 'true', 'false' or empty.
+    if: github.event.inputs.dry-run != 'true' && github.event.inputs.create-os4-cluster != 'false'
     uses: ./.github/workflows/create-cluster.yml
     secrets: inherit
     with:
@@ -371,10 +404,11 @@ jobs:
   create-long-running-cluster:
     name: Create GKE long-running cluster
     needs: [variables, cut-rc]
-    # Cannot use env.DRY_RUN here. `dry-run` can be 'true', 'false' or empty.
+    # Cannot use env.DRY_RUN here. `github.event.inputs.*` can be 'true', 'false' or empty.
     if: >-
       github.event.inputs.dry-run != 'true' &&
-      needs.variables.outputs.rc == '1'
+      needs.variables.outputs.rc == '1' &&
+      github.event.inputs.create-long-cluster != 'false'
     uses: ./.github/workflows/create-cluster.yml
     secrets: inherit
     with:
