Temp CI speedup

diff --git a/.github/workflows/e2e-qa-tests.yaml b/.github/workflows/e2e-qa-tests.yaml
--- a/.github/workflows/e2e-qa-tests.yaml
+++ b/.github/workflows/e2e-qa-tests.yaml
@@ -15,6 +15,10 @@ on:
         description: "Unique job name, e.g. e2e-qa-tests-<cluster flavor>. Used to configure the image prefetcher and name uploaded artifacts. Propagated to tests as CI_JOB_NAME for test dispatching."
         required: true
         type: string
+      cluster-name:
+        description: "Pinned cluster name for debugging purposes."
+        default: ""
+        type: string
       cluster-name-prefix:
         description: "Used as prefix in provisioned cluster names. Maximum 20 characters."
         required: true
@@ -84,6 +88,7 @@ jobs:
       GCP_SERVICE_ACCOUNT_STACKROX_CI: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
       QA_TEST_DEBUG_LOGS: /tmp/qa-tests-backend-logs
       PYTHONUNBUFFERED: "1"
+      CLUSTER_NAME: "${{ inputs.cluster-name }}"
       CLUSTER_NAME_PREFIX: "${{ inputs.cluster-name-prefix }}"
       CLUSTER_NAME_PREFIX_MAX: "20"
     timeout-minutes: ${{ inputs.job-timeout-minutes }}
@@ -91,8 +96,8 @@ jobs:
       - name: Validate workflow input
         run: |
           case "${{ inputs.cluster-provisioning-method }}" in
-            direct-gke|infra) ;;
-            *) echo "::error::Unknown cluster-provisioning-method: '${{ inputs.cluster-provisioning-method }}'. Supported: direct-gke, infra"; exit 1 ;;
+            direct-gke|infra|none) ;;
+            *) echo "::error::Unknown cluster-provisioning-method: '${{ inputs.cluster-provisioning-method }}'. Supported: direct-gke, infra, none"; exit 1 ;;
           esac
 
           if [[ "${#CLUSTER_NAME_PREFIX}" -gt "$CLUSTER_NAME_PREFIX_MAX" ]]; then
@@ -124,6 +129,15 @@ jobs:
 
           cluster_name="${CLUSTER_NAME_PREFIX}-${hash_truncated}"
           echo "CLUSTER_NAME=${cluster_name}" >> "$GITHUB_ENV"
+
+      - name: Check pinned cluster
+        if: inputs.cluster-provisioning-method == 'none'
+        # infractl enforces a 28-char limit for cluster names.
+        run: |
+          if [[ -z "${CLUSTER_NAME:-}" ]]; then
+            echo "::error::For cluster-provisioning-method 'none', the workflow input cluster-name must be provided."
+            exit 1
+          fi
 
       - name: Prepare infra args
         if: inputs.cluster-provisioning-method == 'infra'
@@ -201,10 +215,10 @@ jobs:
           oc version --client
 
       - uses: stackrox/actions/infra/install-infractl@9238e423c3ae1ac4eb0f254cbb98da9daae24d86 # ratchet:stackrox/actions/infra/install-infractl@v1
-        if: inputs.cluster-provisioning-method == 'infra'
+        if: inputs.cluster-provisioning-method == 'infra' || inputs.cluster-provisioning-method == 'none'
 
       - name: Wait for infra cluster and get kubeconfig
-        if: inputs.cluster-provisioning-method == 'infra'
+        if: inputs.cluster-provisioning-method == 'infra' || inputs.cluster-provisioning-method == 'none'
         env:
           INFRA_TOKEN: ${{ secrets.INFRA_TOKEN }}
         timeout-minutes: ${{ inputs.cluster-wait-timeout-minutes }}
