run ui-e2e

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -121,88 +121,88 @@ jobs:
       #  run: |
       #    kubectl delete namespace stackrox || true
 
-      - name: Find or Deploy Stackrox
-        id: rox-installed
-        if: ${{ steps.cluster-exists.outcome != 'failure' }}
-        env:
-          DEPLOY_STACKROX_VIA_OPERATOR: "false"
-          # LOAD_BALANCER: "lb"
-          # SCANNER_SUPPORT: "true"
-          MONITORING_SUPPORT: "false"
-          LOCAL_DEPLOYMENT: "true"
-          ROX_BASELINE_GENERATION_DURATION: "1m"
-          ROX_NETWORK_BASELINE_OBSERVATION_PERIOD: "2m"
-        run: |
-          set +e
-          echo "ROX_SCANNER_V4:${ROX_SCANNER_V4:-}"
-          kubectl get namespace stackrox \
-            || { 
-              if [[ "${CLUSTER,,}" == "openshift" ]]; then
-                  kubectl get scc qatest-anyuid \
-                    || {
-                      kubectl create ns stackrox;
-                      kubectl create -f "qa-tests-backend/src/k8s/scc-qatest-anyuid.yaml";
-                    }
-              fi
-              CI=true ./deploy/deploy-local.sh;
-              find deploy -name password;
-              echo "ROX_ADMIN_PASSWORD=$(cat deploy/*/central-deploy/password)" >> "$GITHUB_ENV";
-            }
+      #- name: Find or Deploy Stackrox
+      #  id: rox-installed
+      #  if: ${{ steps.cluster-exists.outcome != 'failure' }}
+      #  env:
+      #    DEPLOY_STACKROX_VIA_OPERATOR: "false"
+      #    # LOAD_BALANCER: "lb"
+      #    # SCANNER_SUPPORT: "true"
+      #    MONITORING_SUPPORT: "false"
+      #    LOCAL_DEPLOYMENT: "true"
+      #    ROX_BASELINE_GENERATION_DURATION: "1m"
+      #    ROX_NETWORK_BASELINE_OBSERVATION_PERIOD: "2m"
+      #  run: |
+      #    set +e
+      #    echo "ROX_SCANNER_V4:${ROX_SCANNER_V4:-}"
+      #    kubectl get namespace stackrox \
+      #      || { 
+      #        if [[ "${CLUSTER,,}" == "openshift" ]]; then
+      #            kubectl get scc qatest-anyuid \
+      #              || {
+      #                kubectl create ns stackrox;
+      #                kubectl create -f "qa-tests-backend/src/k8s/scc-qatest-anyuid.yaml";
+      #              }
+      #        fi
+      #        CI=true ./deploy/deploy-local.sh;
+      #        find deploy -name password;
+      #        echo "ROX_ADMIN_PASSWORD=$(cat deploy/*/central-deploy/password)" >> "$GITHUB_ENV";
+      #      }
 
-      - name: Stackrox service and auth lookup
-        id: stackrox-api
-        if: ${{ steps.rox-installed.outcome != 'failure' }}
-        timeout-minutes: 5
-        continue-on-error: true
-        run: |
-          set +e
-          set -x
-          ls -latr /tmp/
-          if [[ -e "${KUBECONFIG:-}" ]]; then
-            if [[ -z "${ROX_ADMIN_PASSWORD:+set}" ]]; then
-              password="${ROX_ADMIN_PASSWORD:-$(cat "${KUBECONFIG%kubeconfig}admin-password")}"
-              password="${password:-$(kubectl -n stackrox get secret admin-pass -o json | jq -er '.data.password // ""' | base64 -d)}"
-              password="${password:-$(kubectl -n stackrox get secret central-htpasswd -o json | jq -er '.data.password // ""' | base64 -d)}"
-              echo "ROX_USERNAME=admin" | tee -a "$GITHUB_ENV"
-              echo "ROX_ADMIN_PASSWORD=${password}" >> "$GITHUB_ENV"
-            fi
-            if [[ -z "${API_HOSTNAME:-}" || ( $API_HOSTNAME == 'localhost' && -z "$(pgrep -F /tmp/forward.pid)" ) ]]; then
-              API_HOSTNAME=$(kubectl -n stackrox get route central -o jsonpath='{.status.ingress[0].host}')
-              API_HOSTNAME=${API_HOSTNAME:-$(kubectl -n stackrox get service central-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].ip}')}
-              API_HOSTNAME=${API_HOSTNAME:-localhost}
-              echo "API_HOSTNAME=${API_HOSTNAME}" | tee -a "$GITHUB_ENV"
-              API_PORT=${API_PORT:-$(kubectl -n stackrox get route central -o jsonpath='{.spec.port.targetPort}')}
-              API_PORT=${API_PORT:-$(kubectl -n stackrox get service central-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].port}')}
-              API_PORT=${API_PORT//https/443}
-              if [[ "$API_HOSTNAME" == 'localhost' ]]; then
-                nohup kubectl -n stackrox port-forward svc/central 8000:443 &
-                echo $! | tee /tmp/forward.pid
-                API_PORT=8000
-              fi
-              API_PORT=${API_PORT:-443}
-              echo "API_HOSTNAME=${API_HOSTNAME}" | tee -a "$GITHUB_ENV"
-              echo "API_PORT=${API_PORT}" | tee -a "$GITHUB_ENV"
-            fi
-          fi
-          echo "API_ENDPOINT=${API_HOSTNAME:-localhost}:${API_PORT:-8000}" | tee -a "$GITHUB_ENV"
+      #- name: Stackrox service and auth lookup
+      #  id: stackrox-api
+      #  if: ${{ steps.rox-installed.outcome != 'failure' }}
+      #  timeout-minutes: 5
+      #  continue-on-error: true
+      #  run: |
+      #    set +e
+      #    set -x
+      #    ls -latr /tmp/
+      #    if [[ -e "${KUBECONFIG:-}" ]]; then
+      #      if [[ -z "${ROX_ADMIN_PASSWORD:+set}" ]]; then
+      #        password="${ROX_ADMIN_PASSWORD:-$(cat "${KUBECONFIG%kubeconfig}admin-password")}"
+      #        password="${password:-$(kubectl -n stackrox get secret admin-pass -o json | jq -er '.data.password // ""' | base64 -d)}"
+      #        password="${password:-$(kubectl -n stackrox get secret central-htpasswd -o json | jq -er '.data.password // ""' | base64 -d)}"
+      #        echo "ROX_USERNAME=admin" | tee -a "$GITHUB_ENV"
+      #        echo "ROX_ADMIN_PASSWORD=${password}" >> "$GITHUB_ENV"
+      #      fi
+      #      if [[ -z "${API_HOSTNAME:-}" || ( $API_HOSTNAME == 'localhost' && -z "$(pgrep -F /tmp/forward.pid)" ) ]]; then
+      #        API_HOSTNAME=$(kubectl -n stackrox get route central -o jsonpath='{.status.ingress[0].host}')
+      #        API_HOSTNAME=${API_HOSTNAME:-$(kubectl -n stackrox get service central-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].ip}')}
+      #        API_HOSTNAME=${API_HOSTNAME:-localhost}
+      #        echo "API_HOSTNAME=${API_HOSTNAME}" | tee -a "$GITHUB_ENV"
+      #        API_PORT=${API_PORT:-$(kubectl -n stackrox get route central -o jsonpath='{.spec.port.targetPort}')}
+      #        API_PORT=${API_PORT:-$(kubectl -n stackrox get service central-loadbalancer -o jsonpath='{.status.loadBalancer.ingress[0].port}')}
+      #        API_PORT=${API_PORT//https/443}
+      #        if [[ "$API_HOSTNAME" == 'localhost' ]]; then
+      #          nohup kubectl -n stackrox port-forward svc/central 8000:443 &
+      #          echo $! | tee /tmp/forward.pid
+      #          API_PORT=8000
+      #        fi
+      #        API_PORT=${API_PORT:-443}
+      #        echo "API_HOSTNAME=${API_HOSTNAME}" | tee -a "$GITHUB_ENV"
+      #        echo "API_PORT=${API_PORT}" | tee -a "$GITHUB_ENV"
+      #      fi
+      #    fi
+      #    echo "API_ENDPOINT=${API_HOSTNAME:-localhost}:${API_PORT:-8000}" | tee -a "$GITHUB_ENV"
 
-      - name: Stackrox API test
-        if: ${{ steps.stackrox-api.outcome != 'failure' }}
-        run: |
-          if [[ "${API_HOSTNAME:-}" == 'localhost' && -e /tmp/forward.pid ]]; then 
-            cat /tmp/forward.pid
-            ps -ef | grep kube || true
-          fi
+      #- name: Stackrox API test
+      #  if: ${{ steps.stackrox-api.outcome != 'failure' }}
+      #  run: |
+      #    if [[ "${API_HOSTNAME:-}" == 'localhost' && -e /tmp/forward.pid ]]; then 
+      #      cat /tmp/forward.pid
+      #      ps -ef | grep kube || true
+      #    fi
 
-          curl -sk -u "${ROX_USERNAME}:${ROX_ADMIN_PASSWORD}" "https://${API_ENDPOINT}/v1/clusters" | jq '.'
+      #    curl -sk -u "${ROX_USERNAME}:${ROX_ADMIN_PASSWORD}" "https://${API_ENDPOINT}/v1/clusters" | jq '.'
 
-      - name: Get secured cluster name
-        if: ${{ steps.stackrox-api.outcome != 'failure' }}
-        run: |
-          echo "Groovy tests expect a secured cluster. Default name is 'remote' but the Infra demo clusters set names like 'production'. Look up what secured clusters exist:"
-          set -x
-          CLUSTER_INFO=$(curl -sk -u "${ROX_USERNAME}:${ROX_ADMIN_PASSWORD}" "https://${API_ENDPOINT}/v1/clusters")
-          echo "REMOTE_CLUSTER_NAME=$(jq -r '(.clusters[] | select(.name == "production") | .name) // .clusters[0].name' <<<"$CLUSTER_INFO")" | tee -a "$GITHUB_ENV"
+      #- name: Get secured cluster name
+      #  if: ${{ steps.stackrox-api.outcome != 'failure' }}
+      #  run: |
+      #    echo "Groovy tests expect a secured cluster. Default name is 'remote' but the Infra demo clusters set names like 'production'. Look up what secured clusters exist:"
+      #    set -x
+      #    CLUSTER_INFO=$(curl -sk -u "${ROX_USERNAME}:${ROX_ADMIN_PASSWORD}" "https://${API_ENDPOINT}/v1/clusters")
+      #    echo "REMOTE_CLUSTER_NAME=$(jq -r '(.clusters[] | select(.name == "production") | .name) // .clusters[0].name' <<<"$CLUSTER_INFO")" | tee -a "$GITHUB_ENV"
 
       - run: go get github.com/stackrox/scanner
 
@@ -216,6 +216,7 @@ jobs:
           install --mode 755 /tmp/oc /usr/local/bin/
           install --mode 755 /tmp/kubectl /usr/local/bin/
 
+      # UI e2e - Cypress tests
       - run: |
           set +e
           set -x
@@ -224,32 +225,47 @@ jobs:
           ACS_API_SERVICE_URL="${API_ENDPOINT}"
           setup_automation_flavor_e2e_cluster "${CI_JOB_NAME}"
 
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: wrapper
-          #cache-read-only: false
-          cache-overwrite-existing: true
-          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
+      - run: |
+          set +e
+          set -x
+          export DEPLOY_STACKROX_VIA_OPERATOR=true
+          export INSTALL_COMPLIANCE_OPERATOR=true
+          export ORCHESTRATOR_FLAVOR=openshift
 
-      - timeout-minutes: 10
-        run: |
-          make -C qa-tests-backend compile
+          #DEPLOY_DIR="deploy/${ORCHESTRATOR_FLAVOR}"
+          #HOSTALIASES=/tmp/hostaliases
+          #UI_BASE_URL (set to either "https://central-lb:443" or "https://localhost:${LOCAL_PORT}")
+          #make -C ui test-e2e, so these environment variables will be available during that execution.
 
-      - timeout-minutes: 35
-        run: |
-          export TEST_TARGET="smoke-test"
-          cd qa-tests-backend && ./gradlew testSMOKE --fail-fast
+          tests/e2e/run-ui-e2e.sh
 
-      - timeout-minutes: 35
-        run: |
-          export TEST_TARGET="bat-test"
-          cd qa-tests-backend && ./gradlew testParallelBAT testBAT --fail-fast --warn
+      # QA e2e - groovy tests
+      #- name: Setup Gradle
+      #  uses: gradle/actions/setup-gradle@v4
+      #  with:
+      #    gradle-version: wrapper
+      #    #cache-read-only: false
+      #    cache-overwrite-existing: true
+      #    cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
 
-      - timeout-minutes: 35
-        run: |
-          export TEST_TARGET="test"
-          cd qa-tests-backend && ./gradlew testParallel testRest --fail-fast --warn
+      #- timeout-minutes: 10
+      #  run: |
+      #    make -C qa-tests-backend compile
+
+      #- timeout-minutes: 35
+      #  run: |
+      #    export TEST_TARGET="smoke-test"
+      #    cd qa-tests-backend && ./gradlew testSMOKE --fail-fast
+
+      #- timeout-minutes: 35
+      #  run: |
+      #    export TEST_TARGET="bat-test"
+      #    cd qa-tests-backend && ./gradlew testParallelBAT testBAT --fail-fast --warn
+
+      #- timeout-minutes: 35
+      #  run: |
+      #    export TEST_TARGET="test"
+      #    cd qa-tests-backend && ./gradlew testParallel testRest --fail-fast --warn
 
       - name: Check shared dir and artifacts
         if: always()
