Add workload generation on GKE

diff --git a/.github/workflows/performance-tests.yml b/.github/workflows/performance-tests.yml
--- a/.github/workflows/performance-tests.yml
+++ b/.github/workflows/performance-tests.yml
@@ -3,7 +3,7 @@ on:
   workflow_dispatch:
   push:
     branches:
-    - hack2023/k6-ci-pipeline-tests
+      - hack2023/k6-ci-pipeline-tests
 jobs:
   run-parameters:
     name: Run parameters
@@ -25,6 +25,7 @@ jobs:
     env:
       # TODO: dynamic name should be used
       NAME: k6-test
+      SCALE_CLUSTER_NAME: k6-test-gke
       KUBECONFIG: artifacts/kubeconfig
       INFRA_TOKEN: ${{secrets.INFRA_TOKEN}}
       USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
@@ -41,7 +42,6 @@ jobs:
           flavor: demo
           name: k6-test
           lifespan: 24h
-#          args: main-image=quay.io/rhacs-eng/main:4.2.0
           wait: "true"
 
       # Fetch artifacts
@@ -55,7 +55,6 @@ jobs:
         with:
           install_components: "gke-gcloud-auth-plugin"
       - name: Download artifacts
-        id: artifacts
         run: |
           infractl artifacts "${NAME//./-}" --download-dir artifacts >> "$GITHUB_STEP_SUMMARY"
 
@@ -76,3 +75,83 @@ jobs:
       - name: Output results
         run: |
           cat results.json
+
+      #######################################
+      # Scale cluster with generic workload #
+      #######################################
+
+      # Create scale cluster with larger nodes.
+      - uses: stackrox/actions/infra/create-cluster@main
+        with:
+          token: ${{ secrets.INFRA_TOKEN }}
+          flavor: gke-default
+          name: ${{ env.SCALE_CLUSTER_NAME }}
+          lifespan: 12h
+          args: nodes=3,machine-type=e2-standard-32
+          wait: true
+
+      # Fetch artifacts
+      - uses: stackrox/actions/infra/install-infractl@v1
+      - name: Test cluster readiness
+        run: |
+          STATUS=$(infractl get "${NAME//./-}" --json | jq -r .Status)
+          if [ "$STATUS" != "READY" ]; then
+            exit 1
+          fi
+      - uses: "google-github-actions/auth@v1"
+        with:
+          # TODO: Add new service account
+          credentials_json: "${{ secrets.GCP_RELEASE_AUTOMATION_SA }}"
+      - name: "Set up Cloud SDK"
+        uses: "google-github-actions/setup-gcloud@v1"
+        with:
+          install_components: "gke-gcloud-auth-plugin"
+      - name: Download artifacts
+        run: |
+          infractl artifacts "${NAME//./-}" --download-dir artifacts >> "$GITHUB_STEP_SUMMARY"
+
+      # Install Central + CentralDB
+      # - uses: stackrox/actions/release/wait-for-image@main
+      #   with:
+      #     token: ${{ secrets.QUAY_BEARER_TOKEN }}
+      #     image: rhacs-eng/main:4.2.0
+
+      - name: Install Central
+        run: |
+          infractl artifacts "${SCALE_CLUSTER_NAME//./-}" --download-dir artifacts >> "$GITHUB_STEP_SUMMARY"
+
+      - name: Launch central services
+        env:
+          # TODO: use PR tag!
+          MAIN_IMAGE_REPO: "quay.io/rhacs-eng/main"
+          MAIN_IMAGE_TAG: "4.2.0"
+          ROX_POSTGRES_DATASTORE: "true"
+          REGISTRY_USERNAME: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
+          REGISTRY_PASSWORD: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
+        run: |
+          "${{ github.workspace }}"/scale/dev/launch_central.sh
+
+          # Required for k6 tests to run.
+          echo "ROX_ADMIN_PASSWORD=$(cat ${{ github.workspace }}/deploy/k8s/central-deploy/password)" >> "$GITHUB_ENV"
+
+      # TODO: Find better way to wait for finished workload generation.
+      - name: Generate workload
+        run: |
+          kubectl -n stackrox port-forward deploy/central 8000:8443 > /dev/null 2>&1 &
+          sleep 20
+          "${{ github.workspace }}"/scale/dev/run-many.sh default 3
+          sleep 120
+
+      - name: Run local k6 test
+        uses: grafana/k6-action@v0.3.0
+        env:
+          HOST: "https://localhost:8000"
+        with:
+          filename: tests/performance/tests/testK6Integration.js
+          flags: --out json=results.json --iterations 10 --duration 20m
+
+      - name: Output full results
+        run: |
+          cat results.json
+
+      # TODO: with generic clusters add step to cleanup cluster after run!!!
