更新 scanner-versioned-definitions-update.yaml
Co-authored-by: J. Victor Martins <jvdm@sdf.org>

diff --git a/.github/workflows/scanner-versioned-definitions-update.yaml b/.github/workflows/scanner-versioned-definitions-update.yaml
--- a/.github/workflows/scanner-versioned-definitions-update.yaml
+++ b/.github/workflows/scanner-versioned-definitions-update.yaml
@@ -49,19 +49,19 @@ jobs:
       run: |
         set -eu
         since_time=$(date -u -d '24 hours ago' '+%a, %d %b %Y %H:%M:%S GMT')
-          NVD_BUNDLE_TYPE=${{ github.event.inputs.job || 'nvd-api' }}
-          case "$NVD_BUNDLE_TYPE" in
-              nvd-api)
-                  nvd_file=nvd-api.zip
-                  ;;
-              nvd-feeds)
-                  nvd_file=nvd-feeds.zip
-                  ;;
-              ,*)
-                  echo >&2 "error: invalid NVD bundle type '$NVD_BUNDLE_TYPE'"
-                  exit 1
-          esac
-          url="https://definitions.stackrox.io/v4/nvd/$nvd_file"
+        NVD_BUNDLE_TYPE=${{ github.event.inputs.job || 'nvd-api' }}
+        case "$NVD_BUNDLE_TYPE" in
+            nvd-api)
+                nvd_file=nvd-api.zip
+                ;;
+            nvd-feeds)
+                nvd_file=nvd-feeds.zip
+                ;;
+            ,*)
+                echo >&2 "error: invalid NVD bundle type '$NVD_BUNDLE_TYPE'"
+                exit 1
+        esac
+        url="https://definitions.stackrox.io/v4/nvd/$nvd_file"
 
         code=$(curl \
             -o nvd.zip \
