fix(scanner): RC handling in vulnerability streams

diff --git a/.github/workflows/scanner-versioned-definitions-update.yaml b/.github/workflows/scanner-versioned-definitions-update.yaml
--- a/.github/workflows/scanner-versioned-definitions-update.yaml
+++ b/.github/workflows/scanner-versioned-definitions-update.yaml
@@ -10,6 +10,20 @@ on:
     - synchronize
   workflow_dispatch:
     inputs:
+      stream:
+        description: "Vulnerability bundle version stream to build (typically vN, eg. v2)."
+        required: false
+      ga_ref:
+        description: >
+          WARNING - THIS WLL UPDATE A GA BUNDLE STREAM: Sets the git reference
+          to build a bundle that will be uploaded to the GA version stream.
+        required: false
+      rc_ref:
+        description: >
+          Sets the git reference to build a bundle that will be uploaded to the
+          release candidate version stream, appending `-rc` to the version
+          stream vN (eg. v2-rc).
+        required: false
       job:
         type: choice
         description: "Choose the NVD source"
@@ -32,8 +46,44 @@ jobs:
         fetch-depth: 0
     - name: Parse VULNERABILITY_BUNDLE_VERSION
       id: set-versions
+      env:
+        INPUT_GA_REF: ${{ github.event.inputs.ga_ref || '' }}
+        INPUT_RC_REF: ${{ github.event.inputs.rc_ref || '' }}
+        INPUT_STREAM: ${{ github.event.inputs.stream || '' }}
       run: |
         set -o pipefail
+
+        if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
+            # Validate input.
+            if [ -n "$INPUT_GA_REF" ] && [ -n "$INPUT_RC_REF" ]; then
+                echo >&2 "abort: invalid input: you cannot provide both 'ga_ref' and 'rc_ref'"
+                exit 1
+            fi
+            if [ -z "$INPUT_GA_REF" ] && [ -z "$INPUT_RC_REF" ] && [ -n "$INPUT_STREAM" ]; then
+                echo >&2 "abort: invalid input: when specifying 'stream', you must set 'ga_ref' or 'rc_ref'"
+                exit 1
+            fi
+
+            # Determine the reference.
+            if [ -n "$INPUT_GA_REF" ]; then
+                ref="$INPUT_GA_REF"
+            fi
+            if [ -n "$INPUT_RC_REF" ]; then
+                ref="$INPUT_RC_REF"
+                allow_rc=true
+            fi
+            if [ -z "$ref" ]; then
+                echo >&2 "abort: invalid input: could not determine the reference"
+                exit 1
+            fi
+
+            # Configure environment to generate the matrix with versions and
+            # references.
+            export SCANNER_BUNDLE_STREAM="$INPUT_STREAM"
+            export SCANNER_BUNDLE_REFERENCE="$ref"
+            export SCANNER_RELEASE_ALLOW_RC="$allow_rc"
+        fi
+
         EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
         echo "versions<<$EOF" >> "$GITHUB_OUTPUT"
         ./.github/workflows/scripts/scanner-get-released-tags.sh | tee -a "$GITHUB_OUTPUT"
@@ -357,10 +407,17 @@ jobs:
             gsutil -m cp -r "$dir" gs://definitions.stackrox.io/v4/vulnerability-bundles/
           fi
         done
+
+    - name: Update downstream dev
+      # Run on schedule or when dispatched to build "dev" (only possible if RC was not requested).
+      if: github.event_name == 'schedule' || (github.event.inputs.rc_ref == '' && github.event.inputs.stream == 'dev')
+      run: |
         echo "Copy upstream dev (dev) to downstream dev (1.0.0)"
         gsutil cp -r gs://definitions.stackrox.io/v4/vulnerability-bundles/dev/* gs://definitions.stackrox.io/v4/vulnerability-bundles/1.0.0/
 
     - name: Copy v1 to pre-versioned bundles
+      # Run on schedule or when dispatched to build "GA" (only possible if RC was not requested).
+      if: github.event.inputs.rc_ref == ''
       run: |
         # Only execute if v1 files were created by the build job.
         if ! [ -d "definitions_files/v1" ]; then
