test Slack curl

diff --git a/.github/workflows/scanner-versioned-definitions-update.yaml b/.github/workflows/scanner-versioned-definitions-update.yaml
--- a/.github/workflows/scanner-versioned-definitions-update.yaml
+++ b/.github/workflows/scanner-versioned-definitions-update.yaml
@@ -180,8 +180,9 @@ jobs:
     - name: Check failed updaters and notify Slack
       run: |
         if [ -s bundles/status.json ] && [ "$(jq '.failed_updaters | length' bundles/status.json)" -gt 0 ]; then
+          failed_updaters=$(jq -r '.failed_updaters | join(",")' bundles/status.json)
           curl -X POST -H 'Content-type: application/json' \
-            --data "{\"text\":\"<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow ${{ github.workflow }}> failed in repository ${{ github.repository }}: One or more Scanner updaters failed\"}" \
+            --data "{\"text\":\"<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Workflow ${{ github.workflow }}> failed in repository ${{ github.repository }}: One or more Scanner updaters failed. Failed updaters: ${failed_updaters}\"}" \
             ${{ secrets.SLACK_ONCALL_SCANNER_WEBHOOK }}
           exit 1
         fi
@@ -265,6 +266,22 @@ jobs:
         mkdir -p "$dir"
         cp -r "definitions/${{ github.event.pull_request.number }}/." "$dir/"
         gsutil -m cp -r "$dir" "gs://scanner-v4-test/vulnerability-bundles/"
+
+    # Testing only
+    - name: Check failed updaters and notify Slack
+      run: |
+        if [ -s bundles/status.json ] && [ "$(jq '.failed_updaters | length' bundles/status.json)" -gt 0 ]; then
+          failed_updaters=$(jq -r '.failed_updaters | join(",")' bundles/status.json)
+          echo "Failed updaters: $failed_updaters"
+
+          message=$(jq -n \
+            --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" --arg workflow "${{ github.workflow }}" \
+            --arg repo "${{ github.repository }}" --arg updaters "$failed_updaters" \
+            '{text: ("<\($url)|Workflow \($workflow)> failed in repository \($repo): One or more Scanner updaters failed. Failed updaters: \($updaters)") }')
+
+          curl -X POST -H 'Content-type: application/json' --data "$message" ${{ secrets.SLACK_ONCALL_SCANNER_WEBHOOK }}
+          exit 1
+        fi
 
   upload-definitions:
     needs:
