Update .github/workflows/scanner-versioned-definitions-update.yaml
Co-authored-by: Ross Tannenbaum <rtannenb@redhat.com>

diff --git a/.github/workflows/scanner-versioned-definitions-update.yaml b/.github/workflows/scanner-versioned-definitions-update.yaml
--- a/.github/workflows/scanner-versioned-definitions-update.yaml
+++ b/.github/workflows/scanner-versioned-definitions-update.yaml
@@ -243,7 +243,7 @@ jobs:
     - name: Sanity check NVD zip
       run: |
         if [ ! -f ./nvd.zip ]; then
-          echo "nvd.zip not found!"
+          echo >&2  "nvd.zip not found!"
           exit 1
         fi
 
