Print debug info when ref is `github.event.pull_request.head.sha`

diff --git a/.github/workflows/scanner-build.yaml b/.github/workflows/scanner-build.yaml
--- a/.github/workflows/scanner-build.yaml
+++ b/.github/workflows/scanner-build.yaml
@@ -23,10 +23,39 @@ jobs:
       uses: actions/checkout@v4
       with:
         ref: ${{ github.event.pull_request.head.sha }}
+        # ref: ${{ github.head_ref }}
 
     - name: Define the matrix for build jobs
       id: define-scanner-job-matrix
       run: |
+        echo -e "\nDebug output\n"
+
+        echo -e "\n  github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}"
+        echo -e "\n  github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
+        echo -e "\n  github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
+        echo -e "\n  GITHUB_SHA: $GITHUB_SHA"
+        echo -e "\n  GITHUB_REF: $GITHUB_REF"
+
+        echo -en "\n  git rev-parse HEAD: "
+        git rev-parse HEAD
+
+        echo -e "\n  git status:"
+        git status
+
+        echo -e "\n  all branches that contain current commit:"
+        git branch --contains "$(git rev-parse HEAD)"
+
+        echo -e "\n  log of $GITHUB_SHA:"
+        git log --max-count=6 "$GITHUB_SHA" || echo "git log failed"
+
+        echo -e "\n  git show-ref:"
+        git show-ref || echo "git show-ref failed"
+
+        echo -e "\n  current log: "
+        git log --max-count=6 || echo "git log failed"
+
+        echo -e "\nEnd of debug output\n"
+
         source './scripts/ci/lib.sh'
 
         # If goarch is updated, be sure to update architectures in "push-scanner-manifests" below.
